### ISSUE TITLE
solver/namachan 評価値の蓄積

### ISSUE THREAD

**Issue by namachan10777** [nitk-pm/Procon#109]

**Comment by Mackyson** [comment]
評価値の累積は評価値は高いけど間違ってる初手のミスをものすごく引きずるので、ノードを展開する前に現在のノードの評価値に×0.1~0.5するといいと思います。

**Comment by Mackyson** [comment]
ちなみにビームサーチから愚直にchokudaiサーチにしたSyntaxではたぶん無理です。

**Comment by namachan10777** [comment]
なるほど。ありがとう。
