### ISSUE TITLE
ピースファイルとフレームファイルの統合

### ISSUE THREAD

**Issue by namachan10777** [nitk-pm/Procon#156]

**Comment by namachan10777** [comment]
#157

**Comment by namachan10777** [comment]
pyencoderとsolver/Mackysonに変更が必要だと思うので、ピースファイルとフレームファイルの統合に賛成なら作業お願いします

**Comment by rucm** [comment]
統合自体は賛成
encoderの方はせっかくだからモジュール依存を減らす方向で調整しとく

**Comment by Mackyson** [comment]
現行の形式で全部動いてるし、今後これを開発することはまずないと思うので、変えるメリットはないの思うのですが…

**Comment by namachan10777** [comment]
総合文化祭までに画像処理の実装とQRコード読み取りの改善を行う予定なので、一応はメリットがあるかなと

**Comment by rucm** [comment]
どちらにせよ、encoderがpyqt依存な状態は解消したい
ファイル統合に関しては少し保留しとこう
まずは総文までにどこまでやるか、大雑把でいいから方針決めとこう

**Comment by namachan10777** [comment]
僕は画像処理で解くとこまでしたいんですが、先輩の画像処理のコードってどの程度まで実装されてます?

**Comment by rucm** [comment]
画像上での座標取得まで
スキャナーで撮った画像だと結構精度良くとれるみたい
全てのピースの頂点情報を正確に、とまでは行ってないけどパラメータを調整していけばいけそうな感じはする
リポジトリは[ここ](https://github.com/rucm/opencv-test.git)にあるけど間違えてでかい画像ファイルもまとめてプッシュしちゃったから要注意
動作にOpenCVが必要で、Anacondaをインストールしている場合は
`conda install -c menpo opencv3 `
但し、仮想環境を作ってからインストールを推奨

**Comment by namachan10777** [comment]
なるほど。総文までに最低限のGUIを実装して試してみて、いけそうなら画像処理って感じでどうでしょう。多分画像処理の補正パラメータの調整は研究室でやらないといけないと思うので、動かせるようになったら集まる日を決めるべきかもです。

**Comment by rucm** [comment]
画像さえあればいける
というか、スキャナでやる都合上画像のみの対応になりそうです
目下の課題はグリッド点上に頂点が来るように補正をかける所

**Comment by namachan10777** [comment]
あ、多分その辺はこっちで作ったのでやれます。寸法が完全に正しい形状データさえあれば原点とかグリッド関係なくピース・フレームファイルを生成出来ます

**Comment by rucm** [comment]
なら検出精度向上とGUI作成か
時間見つけてやってみる

**Comment by namachan10777** [comment]
よろしくお願いします。GUIはこっちでも勉強がてらやってみようと思います
