### ISSUE TITLE
solver Mackysonの効率化

### ISSUE THREAD

**Issue by Mackyson** [nitk-pm/Procon#67]
プロファイラによれば現在の処理時間はビーム幅10で15.7s
うち、10.7sがhashsetのハッシュ化で内外判定が2.5秒

**Comment by Mackyson** [comment]
unordered_setからsetへ変更、多角形内部と辺上の点の追加のバグを修復。
ビーム幅10で5.0秒
setの何かの操作（おそらく二分木への追加）に2.0秒、内外判定が1.1秒
ビーム幅を50で70.6秒
setは10.0秒、内外判定は5.2秒
プライオリティキューへの追加が41.0秒

**Comment by Mackyson** [comment]
問題は募集要項に載ってたやつでCPUはi5-2520Mです。

**Comment by rucm** [comment]
実物が送られてきた方はもう試した？

**Comment by Mackyson** [comment]
先ほど試しましたがバグがありました。おそらくは完成していない場合セグフォが出るみたいです。
それからビーム幅1で30個ほど埋めるのに3分半かかっていました。

**Comment by namachan10777** [comment]
#73

**Comment by Mackyson** [comment]
setからvectorへ変更。ピースを置いたとき重なった点を、置く場所の候補から削除してみた。
幅5で124.3秒
内外判定が51.4秒、vector<Position>のアロケーションが30.2秒
幅10で249.6秒
比率はほぼ同じ。

**Comment by Mackyson** [comment]
問題を配られたサンプルに変更しています。

**Comment by Mackyson** [comment]
#87

**Comment by Mackyson** [comment]
・連続で重なる点に評価を付けることで辺の重なりをちょっとだけ考慮できるように
・ハッシュで全く同じ状況のフレームを展開するのを防いだ
・chokudaiサーチにして探索を時間で制御できるようにした
10分で人力による調整で完答可能なレベルの出力

**Comment by Mackyson** [comment]
５分のものと出力が同じだった

**Comment by Mackyson** [comment]
閉領域の数とめちゃくちゃ細い点の数に負の評価をつけた(ビットなので十分速い)

38秒でサンプル完答
