### ISSUE TITLE
pyencoderのバグ?

### ISSUE THREAD

**Issue by namachan10777** [nitk-pm/Procon#68]
sample.txtを-fオプションを付けてencoder.pyでエンコードすると、フレームの始点と終点が重複した結果が帰ってきます。sampls.txt上では重複はしてないように見えました。

**Comment by rucm** [comment]
計算上、始点と終点が同じでないと多角形として処理出来ないんで追加して出力する際に除去してたんだけど、確認したら消すの忘れてました。すぐ修正してプルリク出します。

**Comment by namachan10777** [comment]
分かりました。よろしくお願いします。
